### ISSUE TITLE
Issue on save mounting

### ISSUE THREAD

**Issue by Al4ris** [xXxTheDarkprogramerxXx/PS4_Tools#10]
Greetings,

Is there a limit on the number of files or size when mounting saves?

Cause I tried to mount Days Gone saves and it gives me some kind of full mount error and only mount 16 of the 23 files.

It would be nice if we can select the save files to mount and not every file of each game.

**Comment by Al4ris** [comment]
I respond myself. I've been testing and the mount limit is 16 files, so if on one game you have more files than those, you have to delete the ones don't interest you, to access those who do.

**Comment by xXxTheDarkprogramerxXx** [comment]
Thanks this should be fixed in newer versions up to 9.00 is now supported.

You can mount up to 16 saves.

Or select the ones you want to mount
