### ISSUE TITLE
PS4_Tools Homebrew V1.1 ( unlocker ) and Trophy Unlocker V1.3 Error 550 with port 1337 , 5.05

### ISSUE THREAD

**Issue by KissThis69PL** [xXxTheDarkprogramerxXx/PS4_Tools#13]
Thanks for developing this app :) 
When I go to the Trophy Section, all trophies from all games are immediately unlocked! (5.05) and weird bug when i open trophies  100% but other games have 74% or 50% or even 0% (but when i go inside to see tropies i have all of them)  i wanted to try Trophy Unlocker V1.3 but for some reason i have 550 error ( i have port 1337,turned ftp)

Pictures after using PS4_Tools Homebrew V1.1 unlock all
![20210827_215638_2](https://user-images.githubusercontent.com/80218626/131182813-a2ca2326-17f8-429c-a846-488705a0fcb7.jpg)

![20210827_215655_2](https://user-images.githubusercontent.com/80218626/131182833-ccbedc87-a399-457d-977b-e9dd08b97e36.jpg)

**Comment by xXxTheDarkprogramerxXx** [comment]
Please try homebrew v1.33 should now unlock all dlc trophies as well

**Comment by xXxTheDarkprogramerxXx** [comment]
Please open the issue again if there are any other issues
