### ISSUE TITLE
Trophy Section on PS4_Tools Homebrew V1.1, unlocks all Trophys

### ISSUE THREAD

**Issue by Storm21CH** [xXxTheDarkprogramerxXx/PS4_Tools#4]
Thanks for your great software!
Small problem with PS4_Tools Homebrew V1.1 I think.
When I go to the Trophy Section, all trophies from all games are immediately unlocked! And there is no option to undo it. When I start a game the trophy progress is back to normal, but the trophies have the symbol and timestamp. Tested on 7.55 ...

**Comment by xXxTheDarkprogramerxXx** [comment]
Interesting 

Thanks for the report ill try and replicate the issue on my side.

**Comment by Storm21CH** [comment]
Thank you!
I had tested it twice and it was the same. For info: First came the message load all the trophies, then a message All unlocked. I just pressed the triangle in the main menu.

**Comment by xXxTheDarkprogramerxXx** [comment]
Closed new trophy unlock method (trophy hijack) should fix all issues of this
