### ISSUE TITLE
Winrar file issue

### ISSUE THREAD

**Issue by Muhammad-Radwan** [xXxTheDarkprogramerxXx/PS4_Tools#5]
The source code file downloads successfully but the archive is corrupted

**Comment by xXxTheDarkprogramerxXx** [comment]
Try Izarc or 7Zip
Which file did you download ?

**Comment by Muhammad-Radwan** [comment]
Everything actually, I started with the SC for trophy unlocker, downloads successfully but there is a problem with extracting the file. Then I downloaded the trophies viewer tool, same thing problem

**Comment by xXxTheDarkprogramerxXx** [comment]
Did you try Izarc or 7Zip as mentioned before i downloaded the files and they work fine for me and a few people i asked

**Comment by xXxTheDarkprogramerxXx** [comment]
No reply closing
